version: 2
updates:
  - package-ecosystem: "npm"  # For JavaScript/Node.js projects
    directory: "/"
    schedule:
      interval: "weekly"
    # Correct auto-merge configuration
    open-pull-requests-limit: 10
    # Target specific version updates
    versioning-strategy: auto
    # Configure the PR
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "npm"
      include: "scope"
